name: http download

on: [push, pull_request]

jobs:
  tests:
    name: Tests

    strategy:
      matrix:
        ocaml-version: ["4.14.1"]
        operating-system: [ubuntu-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - name: Install dependencies
        run: opam install --deps-only -t .

      - name: Build
        run: opam exec -- dune build

      - name: Test
        run: opam exec -- dune runtest

      - name: Download
        run: opam exec -- dune exec -- app/hurl.exe https://google.com > /dev/null
